### ISSUE TITLE
Adopt a License

### ISSUE THREAD

**Issue by marios-zindilis** [icons8/titanic#3]
There are good advantages from adopting a license and explicitly mentioning it in your `README` as well as including a `LICENSE` file. See [Why I'm not using your open source project
](https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/) for example. If you want, mention your preferred license in this Issue and I'll send the PR.

**Comment by visualpharm** [comment]
Thank you! We'd prefer either our super serious https://icons8.com/good-boy-license/ or MIT.

**Comment by visualpharm** [comment]
OK, I'm closing it for now; sorry for a delay in the response. We are glad to see your PR though.

**Comment by meduzen** [comment]
> Thank you! We'd prefer either our super serious https://icons8.com/good-boy-license/ or MIT.

That’s great. I think it needs to be mentioned in the repository (and maybe also on the [dedicated page](https://icons8.com/animated-icons)). Otherwise it’s surely open source, but we can’t use it.
